@startmindmap
'https://plantuml.com/mindmap-diagram

caption figure 1
title 英雄设计模型

* 英雄
** ez
*** 属性
**** 血量
**** 攻击力
*** 方法
**** 打架
**** 讲台词
** Jinx
*** 属性
**** 血量 1000
**** 攻击力 20
*** 方法
**** 打架
**** 讲台词


@endmindmap
